name: Docs

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [ 14.x ]
        os: [ ubuntu-latest ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Yarn
        run: |
          cd docs
          yarn
          yarn build
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/aorajs/aora.git
          npx gh-pages -d ./docs/docs-dist -u "github-actions-bot <support+actions@github.com>"
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

