name: Docs

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14.x]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Yarn
        run: cd docs && yarn
      - run: yarn build
      - run: yarn deploy
        env:
          CI: true
          NODE_ENV: test
